name: Sample GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "🎉 Hello from GitHub Actions!"Enter file contents here
